a="abcabcaai"
i=0
count=0
while(i<len(a)):
    if(a[i]=="a"):
        count=count+1
    elif(a[i]=="e"):
        count=count+1
    elif(a[i]=="i"):
        count=count+1
    elif(a[i]=="o"):
        count=count+1
    elif(a[i]=="u"):
        count=count+1
    i=i+1
print(count)